#!/bin/bash
CMD="cd verif/src"
echo $CMD
$CMD

CMD="make"
echo $CMD
$CMD

CMD="cd ../.."
echo $CMD
$CMD

PRELOAD="preload"
if [[ "$2" == "$PRELOAD" ]]; then
   P_PRELOAD=" -D PRELOAD"
fi

# Run all tests add check for pass fail
ALL="all"
if [[ "$1" == "$ALL" ]]; then
   echo ""
   echo ">>>>> Simulation begins <<<<<"
   for filename in verif/src/*.c; do
      printf "%s\t> " $filename | expand -t 30 
      ext=".hex"
      cp -f ${filename/\.c/$ext} load_mem.hex
      ext=".checks"
      cp -f ${filename/\.c/$ext} checks.hex
      iverilog -o ice51.dat -D SIM $P_PRELOAD -c etc/filelist.txt
      vvp ice51.dat -vcd | grep "PASSED\|ERROR" 
   done
   echo ">>>>> Simulation ends <<<<<"
   exit
fi

# Run a single test
ext=".hex"
CMD="cp -f ${1/\.c/$ext} load_mem.hex"
echo $CMD
$CMD

ext=".checks"
CMD="cp -f ${1/\.c/$ext} checks.hex"
echo $CMD
$CMD

CMD="iverilog -o ice51.dat -D SIM $P_PRELOAD -c etc/filelist.txt"
echo $CMD
$CMD

CMD="vvp ice51.dat -vcd > /dev/null 2>&1"
echo $CMD
$CMD 

# Load waves for a single test
WAVES="w"
if [ "$2" == "$WAVES" ] || [ "$3" == "$WAVES" ]; then
   CMD="gtkwave -S etc/signals.tcl ice51.vcd"
   echo $CMD
   $CMD
fi
