#!/bin/bash
echo "========================================================"
echo "Running synth..."
rm -f syn.log
yosys -p 'synth_ice40 -top ice51_top -blif ice51.blif -json ice51.json' rtl/ice51_top.v rtl/ice51.v rtl/mem_1024x8b.v rtl/mem_512x8b.v rtl/dp_mem_512x8b.v> syn.log
cat syn.log | grep -A19 statistics
echo "========================================================"
echo "Running place and route..."
rm -f pnr.log
nextpnr-ice40 --hx8k --json ice51.json --package ct256 --pcf etc/ice51.pcf --asc ice51.asc &> pnr.log
cat pnr.log | grep -A6 "Device utilisation"
echo "========================================================"
echo "Running Timing check..."
icetime -tmd hx8k ice51.asc > ice51.time
cat ice51.time | grep -A20 "Total path delay"
