set sigs [list]

lappend sigs "i_clk"
lappend sigs "i_nrst"
lappend sigs "i_uart_rx"
lappend sigs "o_uart_tx"
lappend sigs "o_code_wr"
lappend sigs "o_code_addr"
lappend sigs "o_code_data"
lappend sigs "i_code_data"
lappend sigs "o_data_wr"
lappend sigs "o_data_addr"
lappend sigs "o_data_data"
lappend sigs "i_data_data"
lappend sigs "smf"
lappend sigs "smd0"
lappend sigs "smd1"
lappend sigs "smd2"
lappend sigs "sme"
lappend sigs "pc"
lappend sigs "pc_next"
lappend sigs "dptr"
lappend sigs "op"
lappend sigs "h_data"
lappend sigs "l_data"
lappend sigs "r\[0\]"
lappend sigs "r\[1\]"
lappend sigs "r\[2\]"
lappend sigs "r\[3\]"
lappend sigs "r\[4\]"
lappend sigs "r\[5\]"
lappend sigs "r\[6\]"
lappend sigs "r\[7\]"
lappend sigs "acc"
lappend sigs "carry"
lappend sigs "b"

set added [ gtkwave::addSignalsFromList $sigs ]
gtkwave::/Time/Zoom/Zoom_Full
