set sigs [list]

lappend sigs "i_clk"
lappend sigs "i_nrst"
lappend sigs "i_uart_rx"
lappend sigs "o_uart_tx"
lappend sigs "o_code_wr"
lappend sigs "o_code_addr"
lappend sigs "o_code_data"
lappend sigs "i_code_data"
lappend sigs "o_data_wr"
lappend sigs "o_data_addr"
lappend sigs "o_data_data"
lappend sigs "i_data_data"
lappend sigs "o_reg_wr"
lappend sigs "o_reg_waddr"
lappend sigs "o_reg_wdata"
lappend sigs "o_reg_raddr"
lappend sigs "i_reg_rdata"
lappend sigs "smf"
lappend sigs "smd0"
lappend sigs "smd1"
lappend sigs "smd2"
lappend sigs "sme"
lappend sigs "pc"
lappend sigs "pc_next"
lappend sigs "dptr"
lappend sigs "op"
lappend sigs "h_data"
lappend sigs "l_data"
lappend sigs "acc"
lappend sigs "carry"
lappend sigs "b"
lappend sigs "sp"
lappend sigs "op_lcall"
lappend sigs "mem\[0\]"
lappend sigs "mem\[1\]"
lappend sigs "mem\[2\]"
lappend sigs "mem\[3\]"
lappend sigs "mem\[4\]"
lappend sigs "mem\[5\]"
lappend sigs "mem\[6\]"
lappend sigs "mem\[7\]"


set added [ gtkwave::addSignalsFromList $sigs ]
gtkwave::/Time/Zoom/Zoom_Full
